[versions]
junit5 = "5.14.2"
junit4 = "4.13.2"
kafkaUtils = "1.3.0"

[libraries]
kafka-bom = { group = "com.bakdata.kafka", name = "kafka-bom", version.ref = "kafkaUtils" }
kafka-streams-utils = { group = "com.bakdata.kafka", name = "kafka-streams-utils", version.ref = "kafkaUtils" }
kafka-clients = { group = "org.apache.kafka", name = "kafka-clients" }
kafka-streams = { group = "org.apache.kafka", name = "kafka-streams" }
kafka-streams-testUtils = { group = "org.apache.kafka", name = "kafka-streams-test-utils" }
kafka-streams-avro-serde = { group = "io.confluent", name = "kafka-streams-avro-serde" }
kafka-streams-protobuf-serde = { group = "io.confluent", name = "kafka-streams-protobuf-serde" }
avro = { group = "org.apache.avro", name = "avro", version = "1.12.1" }
protobuf = { group = "com.google.protobuf", name = "protobuf-java", version = "4.33.4" }
jool = { group = "org.jooq", name = "jool", version = "0.9.15" }

junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit5" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
assertj = { group = "org.assertj", name = "assertj-core", version = "3.27.7" }
log4j-slf4j2 = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version = "2.25.2" }

[plugins]
release = { id = "com.bakdata.release", version = "2.1.0" }
sonar = { id = "com.bakdata.sonar", version = "2.1.0" }
sonatype = { id = "com.bakdata.sonatype", version = "2.1.0" }
lombok = { id = "io.freefair.lombok", version = "8.14.4" }
avro = { id = "com.github.davidmc24.gradle.plugin.avro", version = "1.9.1" }
protobuf = { id = "com.google.protobuf", version = "0.9.6" }
